"""add session status lifecycle

Revision ID: d5eca6d4510a
Revises: 709c87691112
Create Date: 2025-12-19 18:04:25.109594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5eca6d4510a'
down_revision: Union[str, Sequence[str], None] = '709c87691112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('interview_sessions', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'started_at')
    op.drop_column('interview_sessions', 'status')
    # ### end Alembic commands ###
